from box import *
L=[top(),
 row('  WEB / LAPTOP PUNCH RULES            (same form as S2, one more card)              '),
 row(''),
 row('  [x] Allow marking attendance at this zone from a laptop / desktop browser         '),
 row(''),
 row('  Accuracy tolerance for web punches   [ 1000 ] m                                   '),
 row('    A laptop has no GPS. WiFi lookup gives 30-500 m; with no mapped WiFi the        '),
 row('    browser falls back to IP and gives 1-5 km. Mobile fixes use radius / 2.         '),
 row(''),
 row('  Site network (optional)                                                           '),
 row('  [ 103.21.58.0/24  x ]  [ + Add IP range ]                                         '),
 row("    A punch from the site's own connection is accepted whatever the WiFi fix says.  "),
 row('    On a construction site this is usually the strongest signal available.          '),
 row(''),
 row('  [x] Cross-check the coordinate against the request IP  ->  flag on mismatch       '),
 row('      Chrome DevTools can fake the coordinate in 3 clicks. It cannot fake the IP.   '),
 row(''),
 rule(),
 row('  Verdict a web punch can receive at this zone:                                     '),
 row(''),
 row('    in_zone         fits inside radius + accuracy        -> counts                  '),
 row('    ip_allowlisted  came from the site network           -> counts                  '),
 row('    unverified      fix too coarse to decide             -> AR queue                '),
 row('    out_of_zone     accurate fix, clearly outside        -> AR queue                '),
 row('    ip_mismatch     coordinate and IP disagree           -> AR queue + integrity    '),
 row(''),
 row('  "We could not tell" and "you were not there" are DIFFERENT answers.               '),
 row('  Never collapse unverified into absent.                                            '),
 bot()]
print('### S2b — Web / laptop punch rules (new card on the Add Zone form)')
print('```'); print('\n'.join(L)); print('```'); print()
